"""initial schema

Revision ID: 4b1256116e28
Revises:
Create Date: 2026-10-03 14:09:39.242550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1256116e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Name of the question set (1-200 chars)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the question set (max 1000 chars)'),
    sa.Column('job_title', sa.String(length=100), nullable=False, comment='Job title for the question set (2-100 chars)'),
    sa.Column('question_ids', sa.Text(), nullable=False, comment='JSON string of question IDs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.CheckConstraint('LENGTH(job_title) >= 2 AND LENGTH(job_title) <= 100', name='check_set_job_title_length'),
    sa.CheckConstraint('LENGTH(name) >= 1 AND LENGTH(name) <= 200', name='check_set_name_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_set_created_at', 'question_sets', ['created_at'], unique=False)
    op.create_index('idx_set_job_title', 'question_sets', ['job_title'], unique=False)
    op.create_index(op.f('ix_question_sets_id'), 'question_sets', ['id'], unique=False)
    op.create_index(op.f('ix_question_sets_job_title'), 'question_sets', ['job_title'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='ID of the rated question'),
    sa.Column('rating', sa.Float(), nullable=False, comment='Rating value between 1.0 and 5.0'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='Optional user feedback (max 1000 chars)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint('question_id > 0', name='check_question_id_positive'),
    sa.CheckConstraint('rating >= 1.0 AND rating <= 5.0', name='check_rating_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_created_at', 'user_ratings', ['created_at'], unique=False)
    op.create_index('idx_rating_question_id', 'user_ratings', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_ratings_id'), 'user_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_user_ratings_question_id'), 'user_ratings', ['question_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique user email address'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=200), nullable=True, comment='User display name'),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False, comment="Access role: 'user' or 'admin'"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'),
    sa.CheckConstraint("role IN ('user', 'admin')", name='check_user_role'),
    sa.CheckConstraint('LENGTH(email) <= 255', name='check_email_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('question_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ID of the user who performed the action'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='ID of the question the action relates to'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed: generated, viewed, rated, flagged, created, deleted'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional context about the action'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Action timestamp'),
    sa.CheckConstraint("action IN ('generated', 'viewed', 'rated', 'flagged', 'created', 'deleted')", name='check_history_action'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_action', 'question_history', ['action'], unique=False)
    op.create_index('idx_history_created_at', 'question_history', ['created_at'], unique=False)
    op.create_index('idx_history_question_id', 'question_history', ['question_id'], unique=False)
    op.create_index('idx_history_user_id', 'question_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_history_id'), 'question_history', ['id'], unique=False)
    op.create_index(op.f('ix_question_history_question_id'), 'question_history', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_history_user_id'), 'question_history', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ID of the user who created this question'),
    sa.Column('job_title', sa.String(length=100), nullable=False, comment='Job title for the question (2-100 chars)'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='The interview question text (10-2000 chars)'),
    sa.Column('question_type', sa.String(length=50), nullable=False, comment="Type: 'technical', 'behavioral', or 'mixed'"),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Difficulty level 1-5'),
    sa.Column('is_flagged', sa.Boolean(), nullable=False, comment='Whether question is flagged'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='Comma-separated tags'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.CheckConstraint("question_type IN ('technical', 'behavioral', 'mixed')", name='check_question_type'),
    sa.CheckConstraint('LENGTH(job_title) >= 2 AND LENGTH(job_title) <= 100', name='check_job_title_length'),
    sa.CheckConstraint('LENGTH(question_text) >= 10 AND LENGTH(question_text) <= 2000', name='check_question_text_length'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='check_difficulty_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'questions', ['created_at'], unique=False)
    op.create_index('idx_is_flagged', 'questions', ['is_flagged'], unique=False)
    op.create_index('idx_job_title_type', 'questions', ['job_title', 'question_type'], unique=False)
    op.create_index('idx_questions_user_id', 'questions', ['user_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_job_title'), 'questions', ['job_title'], unique=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_table('user_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who uploaded the document'),
    sa.Column('document_type', sa.String(length=20), nullable=False, comment="Type: 'resume' or 'jd'"),
    sa.Column('filename', sa.String(length=255), nullable=True, comment='Original filename'),
    sa.Column('content_text', sa.Text(), nullable=False, comment='Extracted plain-text content'),
    sa.Column('parsed_metadata', sa.JSON(), nullable=True, comment='Structured data extracted from the document'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("document_type IN ('resume', 'jd')", name='check_document_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_type', 'user_documents', ['document_type'], unique=False)
    op.create_index('idx_documents_user_id', 'user_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_documents_id'), 'user_documents', ['id'], unique=False)
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who owns this session'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Hashed session token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Session expiration timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time the session was used'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token_hash', 'user_sessions', ['token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user being interviewed'),
    sa.Column('job_title', sa.String(length=100), nullable=False, comment='Target job title'),
    sa.Column('session_type', sa.String(length=20), nullable=False, comment="Type: 'technical', 'behavioral', or 'mixed'"),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Current adaptive difficulty (1-5)'),
    sa.Column('target_difficulty', sa.Integer(), nullable=False, comment='Starting difficulty chosen by the user'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Status: 'active' or 'completed'"),
    sa.Column('current_turn', sa.Integer(), nullable=False, comment='Number of questions asked so far'),
    sa.Column('max_turns', sa.Integer(), nullable=False, comment='Maximum number of questions in the session'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='Resume/JD document used for personalization'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Completion timestamp'),
    sa.CheckConstraint("session_type IN ('technical', 'behavioral', 'mixed')", name='check_session_type'),
    sa.CheckConstraint("status IN ('active', 'completed')", name='check_session_status'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='check_session_difficulty'),
    sa.ForeignKeyConstraint(['document_id'], ['user_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_index('idx_interview_sessions_user_id', 'interview_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='ID of the parent session'),
    sa.Column('message_id', sa.Integer(), nullable=True, comment='ID of the candidate message being evaluated'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='ID of the question being answered'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who answered'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Overall score (0-10)'),
    sa.Column('technical_score', sa.Float(), nullable=False, comment='Technical correctness (0-10)'),
    sa.Column('communication_score', sa.Float(), nullable=False, comment='Communication clarity (0-10)'),
    sa.Column('completeness_score', sa.Float(), nullable=False, comment='STAR/completeness (0-10)'),
    sa.Column('feedback', sa.JSON(), nullable=True, comment='Structured feedback (strengths, gaps, tips)'),
    sa.Column('model_answer', sa.Text(), nullable=True, comment='AI-generated model answer for comparison'),
    sa.Column('next_action', sa.String(length=30), nullable=True, comment='Orchestrator directive: probe_deeper, follow_up, move_on, redirect'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 10', name='check_overall_score_range'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluations_session_id', 'answer_evaluations', ['session_id'], unique=False)
    op.create_index('idx_evaluations_user_id', 'answer_evaluations', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_id'), 'answer_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_session_id'), 'answer_evaluations', ['session_id'], unique=False)
    op.create_index(op.f('ix_answer_evaluations_user_id'), 'answer_evaluations', ['user_id'], unique=False)
    op.create_table('interview_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='ID of the parent session'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="Role: 'interviewer', 'candidate', or 'system'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='ID of the related question, if any'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional context (scores, follow-ups)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.CheckConstraint("role IN ('interviewer', 'candidate', 'system')", name='check_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session_id', 'interview_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_messages_id'), 'interview_messages', ['id'], unique=False)
    op.create_index(op.f('ix_interview_messages_session_id'), 'interview_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_messages_session_id'), table_name='interview_messages')
    op.drop_index(op.f('ix_interview_messages_id'), table_name='interview_messages')
    op.drop_index('idx_messages_session_id', table_name='interview_messages')
    op.drop_table('interview_messages')
    op.drop_index(op.f('ix_answer_evaluations_user_id'), table_name='answer_evaluations')
    op.drop_index(op.f('ix_answer_evaluations_session_id'), table_name='answer_evaluations')
    op.drop_index(op.f('ix_answer_evaluations_id'), table_name='answer_evaluations')
    op.drop_index('idx_evaluations_user_id', table_name='answer_evaluations')
    op.drop_index('idx_evaluations_session_id', table_name='answer_evaluations')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_index('idx_interview_sessions_user_id', table_name='interview_sessions')
    op.drop_index('idx_interview_sessions_status', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_sessions_token_hash', table_name='user_sessions')
    op.drop_index('idx_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_id'), table_name='user_documents')
    op.drop_index('idx_documents_user_id', table_name='user_documents')
    op.drop_index('idx_documents_type', table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_job_title'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index('idx_questions_user_id', table_name='questions')
    op.drop_index('idx_job_title_type', table_name='questions')
    op.drop_index('idx_is_flagged', table_name='questions')
    op.drop_index('idx_created_at', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_history_user_id'), table_name='question_history')
    op.drop_index(op.f('ix_question_history_question_id'), table_name='question_history')
    op.drop_index(op.f('ix_question_history_id'), table_name='question_history')
    op.drop_index('idx_history_user_id', table_name='question_history')
    op.drop_index('idx_history_question_id', table_name='question_history')
    op.drop_index('idx_history_created_at', table_name='question_history')
    op.drop_index('idx_history_action', table_name='question_history')
    op.drop_table('question_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_ratings_question_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_id'), table_name='user_ratings')
    op.drop_index('idx_rating_question_id', table_name='user_ratings')
    op.drop_index('idx_rating_created_at', table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index(op.f('ix_question_sets_job_title'), table_name='question_sets')
    op.drop_index(op.f('ix_question_sets_id'), table_name='question_sets')
    op.drop_index('idx_set_job_title', table_name='question_sets')
    op.drop_index('idx_set_created_at', table_name='question_sets')
    op.drop_table('question_sets')
    # ### end Alembic commands ###
