-- Database schema provisioning for Interview Helper Agent
--
-- Schema changes are now managed exclusively with Alembic
-- migrations (backend/alembic/). To provision a fresh database:
--
--     docker compose -f docker-compose.yml up -d db
--     docker compose -f docker-compose.yml run --rm backend \
--         /app/venv/bin/alembic upgrade head
--
-- This file is kept only for reference; it is no longer mounted
-- into the postgres image (see docker-compose.yml). Do not add
-- CREATE TABLE statements here — add a migration instead:
--
--     cd backend && alembic revision --autogenerate -m "description"
